apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ironicapis.ironic.openstack.com
spec:
  group: ironic.openstack.com
  names:
    kind: IronicApi
    listKind: IronicApiList
    plural: ironicapis
    singular: ironicapi
  scope: Namespaced
  version: v1alpha1
