apiVersion: apps/v1
kind: Deployment
metadata:
  name: ironic-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ironic-operator
  template:
    metadata:
      labels:
        name: ironic-operator
    spec:
      serviceAccountName: ironic-operator
      containers:
        - name: ironic-operator
          # Replace this with the built image name
          image: "quay.io/yrobla/ironic-operator:v0.0.1"
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - ironic-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ironic-operator"
