---
apiVersion: v1
kind: ConfigMap
metadata:
    name: pxe-settings
data:
    PXE_NIC: eth0
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: dhcp-settings
data:
    USE_EXTERNAL_DHCP: "False"
    CLUSTER_DOMAIN: "edge.testing"
    INITIAL_IP_RANGE: "20"
    FINAL_IP_RANGE: "200"
    DHCP_HOSTS:
        52:54:00:CC:CC:03
