---
apiVersion: v1
kind: ConfigMap
metadata:
    name: images
data:
    KUBERNETES_ENTRYPOINT: "quay.io/stackanetes/kubernetes-entrypoint:v0.3.1"
    IRONIC_API: "quay.io/yrobla/tripleorocky-centos-binary-ironic-api"
    IRONIC_CONDUCTOR: "quay.io/yrobla/tripleorocky-centos-binary-ironic-conductor"
    IRONIC_PXE: "docker.io/tripleorocky/centos-binary-ironic-pxe:current-tripleo"
    NGINX: "docker.io/nginx:1.13.3"
    RABBIT_MANAGEMENT: "docker.io/rabbitmq:3.7-management"
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: pxe-settings
data:
    PXE_NIC: eth0
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: dhcp-settings
data:
    USE_EXTERNAL_DHCP: "False"
    CLUSTER_DOMAIN: "edge.testing"
    INITIAL_IP_RANGE: "20"
    FINAL_IP_RANGE: "200"
    DHCP_HOSTS:
        52:54:00:CC:CC:03
